# count-a.R
# -----------------------------------------------------------------------------
# Author:             Albert Kuo
# Date last modified: May 4, 2021
#
# Count stretches of A's in transcripts

# Packages
suppressPackageStartupMessages({
  library(here)
  library(dplyr)
  library(Biostrings)
  # library(rtracklayer)
  # library(GenomicFeatures)
  # library(BSgenome)
})

# Reference: https://biodatascience.github.io/compbio/bioc/strings.html

# Read FASTA files (generated by download-gencode-files.R)
tx = Biostrings::readDNAStringSet(file = here("mouse_cortex", "salmon_files", "gencode.vM25.transcripts.mouse.fa.gz"))
preandmrna = Biostrings::readDNAStringSet(file = here("mouse_cortex", "salmon_files", "gencode.vM25.preandmrna.mouse.fa.gz"))

# Read transcript to gene mapping
t2g = read.table(here("mouse_cortex", "salmon_files", "gencode.vM25.transcripts.tx2gene.mouse.txt"),
                 col.names = c("transcript_id", "gene_id"))
t2g_preandmrna = read.table(here("mouse_cortex", "salmon_files", "gencode.vM25.preandmrna.tx2gene.mouse.txt"),
                 col.names = c("transcript_id", "gene_id"))

# Save number of stretches of 8 As
# transcripts
matches = vmatchPattern("AAAAAAAA", tx)
transcripts_nA8 = tibble(transcript_id = names(tx),
                         n = elementNROWS(matches)) %>%
  left_join(., t2g, by = "transcript_id")
saveRDS(transcripts_nA8, here("mouse_cortex", "salmon_files", "transcripts_nA8.rds"))

# preandmrna
matches = vmatchPattern("AAAAAAAA", preandmrna)
preandmrna_nA8 = tibble(transcript_id = names(preandmrna),
                        n = elementNROWS(matches)) %>%
  left_join(., t2g_preandmrna, by = "transcript_id")
saveRDS(preandmrna_nA8, here("mouse_cortex", "salmon_files", "preandmrna_nA8.rds"))
